# Generated by Django 4.0.3 on 2022-11-21 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PId', models.AutoField(primary_key=True, serialize=False)),
                ('PName', models.CharField(default='name', max_length=500)),
                ('Description', models.CharField(default='hello', max_length=500)),
                ('DateOfJoining', models.CharField(default='', max_length=50)),
                ('PhotoFileName', models.CharField(default='photoname', max_length=500)),
                ('Price', models.IntegerField(default=0)),
                ('ClosingDate', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='bio..', max_length=500)),
                ('gender', models.CharField(default='XYZ', max_length=10)),
                ('blood', models.CharField(default='x+', max_length=5)),
                ('profession', models.CharField(default='others', max_length=20)),
                ('address', models.CharField(default='Mars', max_length=200)),
                ('contact', models.IntegerField(default=123, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
